import { useEffect, useMemo, useState } from "react";
import BottomNav from "./BottomNav.jsx";
import Modal from "./Modal.jsx";
import {
  buildAgentContext,
  normalizeExperiment,
  normalizeJournalEntry,
  requestKaizenAgent,
  selectEvidenceBackedPatterns,
} from "../lib/kaizenLoop.js";
import { readStorage, writeStorage } from "../utils/storage.js";

const VIEWS = [["today", "Oggi"], ["archive", "Archivio"], ["patterns", "Pattern"], ["experiments", "Esperimenti"]];
const TYPE_LABELS = { fact: "Fatto", observation: "Osservazione", interpretation: "Interpretazione", hypothesis: "Ipotesi", suggestion: "Suggerimento" };
const DRAFT_PREFIX = "kaizen:loop:draft:";

function splitTags(value) { return value.split(",").map((item) => item.trim()).filter(Boolean); }
function joinTags(value) { return (value || []).join(", "); }
function formatDate(value) { return new Intl.DateTimeFormat("it-IT", { weekday: "long", day: "2-digit", month: "long", year: "numeric" }).format(new Date(`${value}T12:00:00`)); }

function DreamCapture({ date, onSave }) {
  const [expanded, setExpanded] = useState(false);
  const [saved, setSaved] = useState(false);
  const [draft, setDraft] = useState({ title: "", text: "", emotions: "", vividness: "", people: "", places: "", themes: "", lucid: "", links: "" });
  function update(key, value) { setDraft((current) => ({ ...current, [key]: value })); }
  function save(noDreamRemembered = false) {
    if (!noDreamRemembered && !draft.text.trim()) return;
    onSave(normalizeJournalEntry({ type: "dream", date, recordedAt: new Date().toISOString(), title: draft.title, text: draft.text, emotions: splitTags(draft.emotions), vividness: draft.vividness, people: splitTags(draft.people), places: splitTags(draft.places), themes: splitTags(draft.themes), lucid: draft.lucid === "" ? null : draft.lucid === "yes", links: splitTags(draft.links), noDreamRemembered, captureMethod: "text" }));
    setDraft({ title: "", text: "", emotions: "", vividness: "", people: "", places: "", themes: "", lucid: "", links: "" });
    setSaved(true); window.setTimeout(() => setSaved(false), 1800);
  }
  return <section className="journal-section dream-capture" aria-labelledby="oneiros-title"><div className="section-heading"><div><p className="eyebrow">Oneiros</p><h2 id="oneiros-title">Che cosa resta del sogno?</h2></div><button aria-expanded={expanded} className="secondary-button compact-button" onClick={() => setExpanded((value) => !value)} type="button">{expanded ? "Meno dettagli" : "Aggiungi dettagli"}</button></div><label className="free-writing"><span>Ricordo libero</span><textarea onChange={(event) => update("text", event.target.value)} placeholder="Scrivi subito, anche solo frammenti…" value={draft.text} /></label>{expanded && <div className="dream-details"><label>Titolo facoltativo<input onChange={(event) => update("title", event.target.value)} value={draft.title} /></label><div className="form-grid two-columns"><label>Emozioni<input onChange={(event) => update("emotions", event.target.value)} placeholder="curiosità, paura…" value={draft.emotions} /></label><label>Vividezza<select onChange={(event) => update("vividness", event.target.value)} value={draft.vividness}><option value="">Non indicata</option>{[1,2,3,4,5].map((value) => <option key={value}>{value}</option>)}</select></label><label>Persone<input onChange={(event) => update("people", event.target.value)} placeholder="separate da virgole" value={draft.people} /></label><label>Luoghi<input onChange={(event) => update("places", event.target.value)} value={draft.places} /></label><label>Temi<input onChange={(event) => update("themes", event.target.value)} value={draft.themes} /></label><label>Lucidità<select onChange={(event) => update("lucid", event.target.value)} value={draft.lucid}><option value="">Non indicata</option><option value="yes">Sogno lucido</option><option value="no">Non lucido</option></select></label></div><label>Collegamenti aggiunti da te<input onChange={(event) => update("links", event.target.value)} placeholder="titoli o riferimenti, separati da virgole" value={draft.links} /></label><small>La struttura conserva il metodo di cattura per una futura voce, senza inviare o registrare audio ora.</small></div>}<div className="journal-inline-actions"><button className="submit-button" disabled={!draft.text.trim()} onClick={() => save(false)} type="button">Salva sogno</button><button className="quiet-button" onClick={() => save(true)} type="button">Nessun sogno ricordato</button><span aria-live="polite" role="status">{saved ? "Salvato" : ""}</span></div></section>;
}

function EveningJournal({ date, entry, intention, onSave, onSaveIntention }) {
  const draftKey = `${DRAFT_PREFIX}${date}`;
  const [draftStatus, setDraftStatus] = useState("");
  const [draft, setDraft] = useState(() => readStorage(draftKey, null) || { freeText: entry?.freeText || "", prompts: { happened: entry?.prompts?.happened || "", progress: entry?.prompts?.progress || "", obstacle: entry?.prompts?.obstacle || "", tomorrow: entry?.prompts?.tomorrow || "" }, metrics: { energy: entry?.metrics?.energy || "", focus: entry?.metrics?.focus || "", satisfaction: entry?.metrics?.satisfaction || "" } });
  useEffect(() => { const timeout = window.setTimeout(() => { writeStorage(draftKey, draft); setDraftStatus("Bozza salvata in locale"); }, 450); return () => window.clearTimeout(timeout); }, [draft, draftKey]);
  function updatePrompt(key, value) { setDraft((current) => ({ ...current, prompts: { ...current.prompts, [key]: value } })); }
  function updateMetric(key, value) { setDraft((current) => ({ ...current, metrics: { ...current.metrics, [key]: value } })); }
  function save() { onSave(normalizeJournalEntry({ ...entry, type: "daily", date, ...draft })); setDraftStatus("Giornata salvata"); }
  return <><section className="journal-section intention-section"><div><p className="eyebrow">Intenzione</p><h2>Una direzione per oggi</h2></div><label><span className="sr-only">Intenzione del giorno</span><textarea onBlur={(event) => onSaveIntention(event.target.value)} onChange={(event) => onSaveIntention(event.target.value)} placeholder="Che qualità o risultato vuoi proteggere oggi?" value={intention || ""} /></label></section><section className="journal-section evening-journal" aria-labelledby="evening-title"><div className="section-heading"><div><p className="eyebrow">Journal serale</p><h2 id="evening-title">Scrivi quanto basta</h2></div><span className="draft-status" aria-live="polite">{draftStatus}</span></div><label className="free-writing"><span>Campo libero</span><textarea onChange={(event) => setDraft((current) => ({ ...current, freeText: event.target.value }))} placeholder="La giornata, in parole tue…" value={draft.freeText} /></label><details className="journal-prompts"><summary>Quattro domande, facoltative</summary><div><label>Che cosa è successo?<textarea onChange={(event) => updatePrompt("happened", event.target.value)} value={draft.prompts.happened} /></label><label>Quale progresso concreto ho fatto?<textarea onChange={(event) => updatePrompt("progress", event.target.value)} value={draft.prompts.progress} /></label><label>Che cosa mi ha ostacolato?<textarea onChange={(event) => updatePrompt("obstacle", event.target.value)} value={draft.prompts.obstacle} /></label><label>Che cosa voglio ricordare o cambiare domani?<textarea onChange={(event) => updatePrompt("tomorrow", event.target.value)} value={draft.prompts.tomorrow} /></label></div></details><div className="journal-metrics"><span>Metriche facoltative</span>{[["energy", "Energia"], ["focus", "Concentrazione"], ["satisfaction", "Soddisfazione"]].map(([key, label]) => <label key={key}>{label}<select onChange={(event) => updateMetric(key, event.target.value)} value={draft.metrics[key]}><option value="">—</option>{[1,2,3,4,5].map((value) => <option key={value}>{value}</option>)}</select></label>)}</div><button className="submit-button" onClick={save} type="button">Salva giornata</button></section></>;
}

function SuggestionModal({ onAccept, onClose, suggestion }) {
  const [draft, setDraft] = useState({ ...suggestion });
  return <Modal labelId="suggestion-title" onClose={onClose}><div className="modal-heading"><div><p className="eyebrow">Conferma esplicita</p><h2 id="suggestion-title">{suggestion.kind === "experiment" ? "Crea esperimento" : suggestion.kind === "action" ? "Crea azione" : "Accetta suggerimento"}</h2></div><button className="ghost-button" onClick={onClose} type="button">Chiudi</button></div><form className="task-form" onSubmit={(event) => { event.preventDefault(); onAccept(draft, draft.title === suggestion.title && draft.description === suggestion.description ? "accepted" : "modified"); }}><label>Titolo<input onChange={(event) => setDraft((value) => ({ ...value, title: event.target.value }))} value={draft.title} /></label><label>Descrizione<textarea onChange={(event) => setDraft((value) => ({ ...value, description: event.target.value }))} value={draft.description} /></label><p className="privacy-note">Nulla verrà creato finché non premi Conferma. L'agente non modifica direttamente i tuoi dati.</p><button className="submit-button" type="submit">Conferma</button></form></Modal>;
}

function AgentPanel({ data, date, onAcceptSuggestion, onSaveInsight, onUpdateFeedback }) {
  const [includeDreams, setIncludeDreams] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [error, setError] = useState("");
  const [pendingSuggestion, setPendingSuggestion] = useState(null);
  const insight = [...data.agentInsights].filter((item) => item.date === date && item.mode === "journal").sort((a, b) => (b.createdAt || "").localeCompare(a.createdAt || ""))[0];
  async function analyze() { setError(""); setIsAnalyzing(true); try { const context = buildAgentContext({ data, date, includeDreams, mode: "journal" }); const analysis = await requestKaizenAgent(context); onSaveInsight({ id: `agent-journal:${date}:${Date.now()}`, date, mode: "journal", includeDreams, inputRefs: context.journalEntries.map((entry) => entry.id), ...analysis, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); } catch (analysisError) { setError(analysisError.message); } finally { setIsAnalyzing(false); } }
  return <section className="journal-section agent-panel" aria-labelledby="agent-title"><div className="section-heading"><div><p className="eyebrow">Agente Kaizen</p><h2 id="agent-title">Analisi prudente, avviata da te</h2></div></div><div className="privacy-disclosure"><strong>Dati inviati in questa analisi</strong><p>Journal recente, azioni aperte, strategie personali e feedback ai suggerimenti. Testi limitati e nessun log del contenuto completo.</p><label className="check-row"><input checked={includeDreams} onChange={(event) => setIncludeDreams(event.target.checked)} type="checkbox" />Includi Oneiros (facoltativo)</label><small>{includeDreams ? "I sogni recenti saranno inclusi come resoconti, non come fatti o diagnosi." : "Oneiros è escluso."}</small></div><button className="submit-button" disabled={isAnalyzing} onClick={analyze} type="button">{isAnalyzing ? "Analisi in corso…" : "Avvia analisi"}</button>{error && <p className="form-error" role="alert">{error}</p>}{insight && <div className="agent-result">{insight.summary && <p className="agent-summary">{insight.summary}</p>}<ul className="statement-list">{(insight.statements || []).map((statement, index) => <li className={`statement statement-${statement.type}`} key={`${statement.type}-${index}`}><span>{TYPE_LABELS[statement.type]}</span><p>{statement.text}</p>{statement.evidence?.length > 0 && <details><summary>{statement.evidence.length} evidenze</summary><ul>{statement.evidence.map((evidence) => <li key={`${evidence.recordId}-${evidence.date}`}><time>{evidence.date}</time> · {evidence.excerpt || evidence.recordId}</li>)}</ul></details>}</li>)}</ul>{insight.suggestions?.length > 0 && <div className="suggestion-list"><h3>Suggerimenti da confermare</h3>{insight.suggestions.map((suggestion) => <article key={suggestion.id}><strong>{suggestion.title}</strong><p>{suggestion.description}</p>{suggestion.feedback ? <span className="feedback-state">{suggestion.feedback === "accepted" ? "Accettato" : suggestion.feedback === "modified" ? "Accettato con modifica" : "Rifiutato"}</span> : <div><button className="secondary-button compact-button" onClick={() => setPendingSuggestion({ insightId: insight.id, suggestion })} type="button">Rivedi e conferma</button><button className="quiet-button" onClick={() => onUpdateFeedback(insight.id, suggestion.id, "rejected")} type="button">Rifiuta</button></div>}</article>)}</div>}</div>}{pendingSuggestion && <SuggestionModal onAccept={(draft, feedback) => { onAcceptSuggestion(draft); onUpdateFeedback(pendingSuggestion.insightId, pendingSuggestion.suggestion.id, feedback); setPendingSuggestion(null); }} onClose={() => setPendingSuggestion(null)} suggestion={pendingSuggestion.suggestion} />}</section>;
}

function EntryModal({ entry, onClose, onDelete, onSave }) {
  const [draft, setDraft] = useState(entry.type === "dream" ? { ...entry, emotions: joinTags(entry.emotions), people: joinTags(entry.people), places: joinTags(entry.places), themes: joinTags(entry.themes) } : { ...entry });
  const [confirmDelete, setConfirmDelete] = useState(false);
  return <Modal className="entry-modal" labelId="entry-editor-title" onClose={onClose}><div className="modal-heading"><div><p className="eyebrow">Archivio Journal</p><h2 id="entry-editor-title">Modifica {entry.type === "dream" ? "Oneiros" : "giornata"}</h2></div><button className="ghost-button" onClick={onClose} type="button">Chiudi</button></div><form className="task-form" onSubmit={(event) => { event.preventDefault(); const value = entry.type === "dream" ? { ...draft, emotions: splitTags(draft.emotions), people: splitTags(draft.people), places: splitTags(draft.places), themes: splitTags(draft.themes) } : draft; onSave(normalizeJournalEntry(value)); }}>{entry.type === "dream" ? <><label>Titolo<input onChange={(event) => setDraft((value) => ({ ...value, title: event.target.value }))} value={draft.title || ""} /></label><label>Ricordo<textarea onChange={(event) => setDraft((value) => ({ ...value, text: event.target.value }))} value={draft.text || ""} /></label><label>Emozioni<input onChange={(event) => setDraft((value) => ({ ...value, emotions: event.target.value }))} value={draft.emotions} /></label></> : <label>Journal<textarea onChange={(event) => setDraft((value) => ({ ...value, freeText: event.target.value }))} value={draft.freeText || ""} /></label>}<div className="modal-actions split-actions"><button className="secondary-button danger-button" onClick={() => confirmDelete ? onDelete(entry.id) : setConfirmDelete(true)} type="button">{confirmDelete ? "Conferma cancellazione" : "Cancella voce"}</button><button className="submit-button" type="submit">Salva modifica</button></div></form></Modal>;
}

function ExperimentModal({ experiment, onClose, onSave }) {
  const [draft, setDraft] = useState({ problem: "", hypothesis: "", behavior: "", ifThen: { if: "", then: "" }, startDate: new Date().toISOString().slice(0,10), durationDays: 7, metric: "", reviewDate: "", status: "planned", result: "", decision: "", isPrimary: false, ...experiment });
  function update(key, value) { setDraft((current) => ({ ...current, [key]: value })); }
  return <Modal className="experiment-modal" labelId="experiment-title" onClose={onClose}><div className="modal-heading"><div><p className="eyebrow">Kaizen verificabile</p><h2 id="experiment-title">{experiment ? "Modifica esperimento" : "Nuovo esperimento"}</h2></div><button className="ghost-button" onClick={onClose} type="button">Chiudi</button></div><form className="task-form" onSubmit={(event) => { event.preventDefault(); if (draft.problem.trim() && draft.behavior.trim()) onSave(normalizeExperiment(draft)); }}><label>Problema osservato<textarea onChange={(event) => update("problem", event.target.value)} value={draft.problem} /></label><label>Ipotesi<textarea onChange={(event) => update("hypothesis", event.target.value)} value={draft.hypothesis} /></label><label>Comportamento da provare<textarea onChange={(event) => update("behavior", event.target.value)} value={draft.behavior} /></label><div className="if-then-row"><label>Se…<input onChange={(event) => update("ifThen", { ...draft.ifThen, if: event.target.value })} value={draft.ifThen?.if || ""} /></label><label>allora…<input onChange={(event) => update("ifThen", { ...draft.ifThen, then: event.target.value })} value={draft.ifThen?.then || ""} /></label></div><div className="form-grid two-columns"><label>Inizio<input onChange={(event) => update("startDate", event.target.value)} type="date" value={draft.startDate} /></label><label>Durata (giorni)<input min="1" onChange={(event) => update("durationDays", event.target.value)} type="number" value={draft.durationDays} /></label><label>Metrica semplice<input onChange={(event) => update("metric", event.target.value)} value={draft.metric} /></label><label>Data revisione<input onChange={(event) => update("reviewDate", event.target.value)} type="date" value={draft.reviewDate} /></label><label>Stato<select onChange={(event) => update("status", event.target.value)} value={draft.status}><option value="planned">Pianificato</option><option value="active">Attivo</option><option value="review">Da rivedere</option><option value="completed">Concluso</option></select></label><label>Decisione<select onChange={(event) => update("decision", event.target.value)} value={draft.decision}><option value="">Da decidere</option><option value="adopt">Adotta</option><option value="modify">Modifica</option><option value="abandon">Abbandona</option></select></label></div><label>Risultato<textarea onChange={(event) => update("result", event.target.value)} value={draft.result} /></label><label className="check-row"><input checked={draft.isPrimary} onChange={(event) => update("isPrimary", event.target.checked)} type="checkbox" />Esperimento principale attivo</label><button className="submit-button" disabled={!draft.problem.trim() || !draft.behavior.trim()} type="submit">Salva esperimento</button></form></Modal>;
}

export default function JournalPage({ activeSection, activeSubsection, data, date, onAcceptSuggestion, onDeleteExperiment, onDeleteJournalEntry, onNavigate, onSaveAgentInsight, onSaveDailyPlan, onSaveExperiment, onSaveJournalEntry, onSetPatternStatus, onUpdateAgentFeedback }) {
  const [view, setView] = useState(activeSubsection || "today");
  const [editingEntry, setEditingEntry] = useState(null);
  const [editingExperiment, setEditingExperiment] = useState(undefined);
  useEffect(() => { if (activeSubsection) setView(activeSubsection); }, [activeSubsection]);
  const todayDaily = data.journalEntries.find((entry) => entry.type === "daily" && entry.date === date);
  const todayPlan = data.dailyPlans.find((plan) => plan.date === date) || { date, intention: "", ifThen: {} };
  const entries = useMemo(() => [...data.journalEntries].sort((a,b) => `${b.date}:${b.recordedAt || b.updatedAt}`.localeCompare(`${a.date}:${a.recordedAt || a.updatedAt}`)), [data.journalEntries]);
  const patterns = useMemo(() => selectEvidenceBackedPatterns(data.agentInsights), [data.agentInsights]);
  function navigate(next) { setView(next); onNavigate("journal", next); }
  function exportJournal() { const blob = new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), journalEntries: data.journalEntries }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `kaizen-journal-${date}.json`; anchor.click(); URL.revokeObjectURL(url); }
  const primaryExperiment = data.experiments.find((item) => item.isPrimary && item.status === "active");
  return <div className="app-shell"><main className="page journal-page"><header className="topbar compact-topbar"><div><p className="eyebrow">Spazio privato</p><h1>Journal</h1></div><p className="brand-mark">Kaizen Loop</p></header><nav className="section-tabs journal-tabs" aria-label="Viste Journal">{VIEWS.map(([key,label]) => <button aria-current={view === key ? "page" : undefined} className={view === key ? "is-selected" : ""} key={key} onClick={() => navigate(key)} type="button">{label}</button>)}</nav>
    {view === "today" && <div className="journal-today"><DreamCapture date={date} onSave={onSaveJournalEntry} /><EveningJournal date={date} entry={todayDaily} intention={todayPlan.intention} onSave={onSaveJournalEntry} onSaveIntention={(intention) => onSaveDailyPlan({ ...todayPlan, intention })} /><AgentPanel data={data} date={date} onAcceptSuggestion={onAcceptSuggestion} onSaveInsight={onSaveAgentInsight} onUpdateFeedback={onUpdateAgentFeedback} /></div>}
    {view === "archive" && <section className="panel journal-archive"><div className="section-heading"><div><p className="eyebrow">Archivio</p><h2>Giornate e Oneiros</h2></div><button className="secondary-button compact-button" onClick={exportJournal} type="button">Esporta JSON</button></div><p className="privacy-note">L'esportazione resta sul dispositivo. Puoi modificare o cancellare ogni voce.</p>{entries.length ? <ul className="archive-entry-list">{entries.map((entry) => <li key={entry.id}><button onClick={() => setEditingEntry(entry)} type="button"><span>{entry.type === "dream" ? "Oneiros" : "Journal"}</span><strong>{entry.type === "dream" ? entry.title || (entry.noDreamRemembered ? "Nessun sogno ricordato" : "Sogno senza titolo") : formatDate(entry.date)}</strong><p>{entry.type === "dream" ? entry.text : entry.freeText}</p><time>{entry.date}</time></button></li>)}</ul> : <p className="empty-state">Nessuna voce. Puoi iniziare da Oggi con poche righe.</p>}</section>}
    {view === "patterns" && <section className="panel pattern-view"><div className="section-heading"><div><p className="eyebrow">Pattern</p><h2>Solo ricorrenze con più evidenze</h2></div><span className="counter">{patterns.length}</span></div>{patterns.length ? <ul className="pattern-list">{patterns.map((pattern) => <li key={pattern.name}><div><span>{pattern.scope} · confidenza {pattern.confidence}</span><strong>{pattern.name}</strong><p>{pattern.description}</p></div><details><summary>{pattern.evidence.length} evidenze su {new Set(pattern.evidence.map((item) => item.date)).size} giorni</summary><ul>{pattern.evidence.map((item) => <li key={`${item.recordId}-${item.date}`}><time>{item.date}</time><p>{item.excerpt || item.recordId}</p></li>)}</ul></details><small>Stato: {pattern.status}</small><div className="pattern-actions"><button className="quiet-button" onClick={() => onSetPatternStatus(pattern.name, "confirmed")} type="button">Conferma</button><button className="quiet-button" onClick={() => onSetPatternStatus(pattern.name, "rejected")} type="button">Respingi</button><button className="quiet-button" onClick={() => onSetPatternStatus(pattern.name, "archived")} type="button">Archivia</button></div></li>)}</ul> : <p className="empty-state">Nessun pattern sufficientemente supportato. Una singola occorrenza resta un'osservazione, non un pattern.</p>}</section>}
    {view === "experiments" && <section className="panel experiments-view"><div className="section-heading"><div><p className="eyebrow">Esperimenti Kaizen</p><h2>Un cambiamento principale alla volta</h2></div><button className="submit-button compact-button" onClick={() => setEditingExperiment(null)} type="button">Nuovo esperimento</button></div>{primaryExperiment && <article className="primary-experiment"><span>Esperimento principale</span><strong>{primaryExperiment.behavior}</strong><p>{primaryExperiment.hypothesis}</p><small>Revisione: {primaryExperiment.reviewDate || "da pianificare"} · metrica: {primaryExperiment.metric || "da definire"}</small></article>}{data.experiments.length ? <ul className="experiment-list">{data.experiments.map((experiment) => <li key={experiment.id}><button onClick={() => setEditingExperiment(experiment)} type="button"><span>{experiment.status}{experiment.isPrimary ? " · principale" : ""}</span><strong>{experiment.problem}</strong><p>{experiment.behavior}</p><small>{experiment.durationDays} giorni · {experiment.decision || "decisione aperta"}</small></button><button className="delete-button labeled-delete" onClick={() => onDeleteExperiment(experiment.id)} type="button">Elimina</button></li>)}</ul> : <p className="empty-state">Nessun esperimento. Creane uno quando hai un problema osservabile e una metrica semplice.</p>}</section>}
  </main><BottomNav activeSection={activeSection} onNavigate={onNavigate} />
  {editingEntry && <EntryModal entry={editingEntry} onClose={() => setEditingEntry(null)} onDelete={(id) => { onDeleteJournalEntry(id); setEditingEntry(null); }} onSave={(entry) => { onSaveJournalEntry(entry); setEditingEntry(null); }} />}
  {editingExperiment !== undefined && <ExperimentModal experiment={editingExperiment} onClose={() => setEditingExperiment(undefined)} onSave={(experiment) => { onSaveExperiment(experiment); setEditingExperiment(undefined); }} />}
  </div>;
}
