import { useEffect, useMemo, useState } from "react";
import BottomNav from "./BottomNav.jsx";
import CalendarPanel from "./CalendarPanel.jsx";
import ClarifyInboxModal from "./ClarifyInboxModal.jsx";
import Modal from "./Modal.jsx";
import UnifiedActions from "./UnifiedActions.jsx";
import WeeklyReview from "./WeeklyReview.jsx";
import AgentAssist from "./AgentAssist.jsx";
import { selectUnifiedActions } from "../lib/kaizenLoop.js";

const SECTIONS = [
  ["inbox", "Inbox"], ["projects", "Progetti"], ["actions", "Prossime azioni"],
  ["waiting", "In attesa"], ["calendar", "Calendario"], ["someday", "Prima o poi / Forse"],
  ["archive", "Archivio"], ["review", "Revisione settimanale"],
];

function ProjectModal({ onClose, onSave, project }) {
  const [draft, setDraft] = useState({ title: "", desiredOutcome: "", status: "active", dueDate: "", lastReviewedAt: "", newActionTitle: "", ...project });
  function update(key, value) { setDraft((current) => ({ ...current, [key]: value })); }
  return <Modal className="project-modal" labelId="project-editor-title" onClose={onClose}><div className="modal-heading"><div><p className="eyebrow">Progetto</p><h2 id="project-editor-title">{project ? "Modifica progetto" : "Nuovo progetto"}</h2></div><button className="ghost-button" onClick={onClose} type="button">Chiudi</button></div><form className="task-form" onSubmit={(event) => { event.preventDefault(); if (draft.title.trim()) onSave(draft); }}><label>Titolo<input autoFocus onChange={(event) => update("title", event.target.value)} value={draft.title} /></label><label>Risultato desiderato<textarea onChange={(event) => update("desiredOutcome", event.target.value)} placeholder="Come apparirà il progetto quando sarà concluso?" value={draft.desiredOutcome || ""} /></label><div className="form-grid two-columns"><label>Stato<select onChange={(event) => update("status", event.target.value)} value={draft.status}><option value="active">Attivo</option><option value="blocked">Bloccato</option><option value="on-hold">In pausa</option><option value="completed">Completato</option></select></label><label>Scadenza<input onChange={(event) => update("dueDate", event.target.value)} type="date" value={draft.dueDate || ""} /></label></div>{!project && <label>Prima prossima azione<input onChange={(event) => update("newActionTitle", event.target.value)} placeholder="Facoltativa, ma consigliata" value={draft.newActionTitle || ""} /></label>}<div className="modal-actions"><button className="submit-button" disabled={!draft.title.trim()} type="submit">Salva progetto</button></div></form></Modal>;
}

function BasicModal({ fields, item, mode, onClose, onDownloadAttachment, onSave }) {
  const [draft, setDraft] = useState({ title: "", description: "", ...item });
  return <Modal labelId="basic-editor-title" onClose={onClose}><div className="modal-heading"><div><p className="eyebrow">Sistema</p><h2 id="basic-editor-title">{mode}</h2></div><button className="ghost-button" onClick={onClose} type="button">Chiudi</button></div><form className="task-form" onSubmit={(event) => { event.preventDefault(); if (draft.title.trim()) onSave(draft); }}><label>Titolo<input autoFocus onChange={(event) => setDraft((value) => ({ ...value, title: event.target.value }))} value={draft.title} /></label>{fields.map((field) => field.type === "textarea" ? <label key={field.key}>{field.label}<textarea onChange={(event) => setDraft((value) => ({ ...value, [field.key]: event.target.value }))} value={draft[field.key] || ""} /></label> : <label key={field.key}>{field.label}<input onChange={(event) => setDraft((value) => ({ ...value, [field.key]: event.target.value }))} type={field.type || "text"} value={draft[field.key] || ""} /></label>)}{item?.attachments?.length > 0 && <div className="attachment-list"><strong>Allegati</strong>{item.attachments.map((attachment) => <button key={attachment.id} onClick={() => onDownloadAttachment?.(attachment)} type="button"><span>{attachment.name}</span><small>{Math.max(1, Math.round(attachment.size / 1024))} KB · Scarica</small></button>)}</div>}<div className="modal-actions"><button className="submit-button" disabled={!draft.title.trim()} type="submit">Salva</button></div></form></Modal>;
}

function EmptyState({ action, children, onAction }) { return <div className="empty-state actionable-empty"><p>{children}</p>{action && <button className="secondary-button compact-button" onClick={onAction} type="button">{action}</button>}</div>; }

export default function SystemPage({ activeSection, activeSubsection, data, date, onActionDelete, onActionOrder, onActionSave, onAddInboxItem, onClarifyInboxItem, onDeleteArchiveItem, onDeleteCalendarItem, onDeleteProject, onDeleteSomedayMaybe, onDeleteWaitingFor, onDownloadArchiveAttachment, onNavigate, onSaveAgentInsight, onSaveArchiveItem, onSaveCalendarItem, onSaveProject, onSaveSomedayMaybe, onSaveWaitingFor, onSaveWeeklyReview, onToggleAction }) {
  const [section, setSection] = useState(activeSubsection || "inbox");
  const [clarifying, setClarifying] = useState(null);
  const [editingProject, setEditingProject] = useState(undefined);
  const [editor, setEditor] = useState(null);
  const actions = useMemo(() => selectUnifiedActions(data), [data]);
  const openInbox = data.inboxItems.filter((item) => item.status === "open");
  useEffect(() => { if (activeSubsection) setSection(activeSubsection); }, [activeSubsection]);
  function go(nextSection) { setSection(nextSection); onNavigate("system", nextSection); }
  const projectsWithOpenActions = new Set(data.projectActions.filter((action) => !action.completed).map((action) => action.projectId));
  const staleThreshold = Date.now() - 14 * 86400000;

  return <div className="app-shell"><main className="page system-page"><header className="topbar compact-topbar"><div><p className="eyebrow">Inventario affidabile</p><h1>Sistema</h1></div><p className="brand-mark">Kaizen Loop</p></header><nav className="section-tabs system-desktop-tabs" aria-label="Sezioni del Sistema">{SECTIONS.map(([key, label]) => <button aria-current={section === key ? "page" : undefined} className={section === key ? "is-selected" : ""} key={key} onClick={() => go(key)} type="button">{label}{key === "inbox" && <span>{openInbox.length}</span>}</button>)}</nav><label className="mobile-section-picker" htmlFor="system-section"><span>Sezione del Sistema</span><select id="system-section" onChange={(event) => go(event.target.value)} value={section}>{SECTIONS.map(([key, label]) => <option key={key} value={key}>{label}{key === "inbox" ? ` (${openInbox.length})` : ""}</option>)}</select></label>

    {section === "inbox" && <section className="panel system-surface"><div className="section-heading"><div><p className="eyebrow">Inbox</p><h2>Decidi cosa significa ogni elemento</h2></div><span className="counter">{openInbox.length}</span></div>{openInbox.length ? <ul className="inbox-list">{openInbox.map((item) => <li key={item.id}><div><strong>{item.originalText}</strong><small>{new Intl.DateTimeFormat("it-IT", { day: "2-digit", month: "short" }).format(new Date(item.createdAt))}</small></div><button className="secondary-button compact-button" onClick={() => setClarifying(item)} type="button">Chiarisci</button></li>)}</ul> : <EmptyState>Inbox vuota. Hai già deciso cosa fare di tutto ciò che hai catturato.</EmptyState>}<AgentAssist data={data} date={date} mode="gtd-clarification" onSaveInsight={onSaveAgentInsight} title="Supporto al chiarimento GTD" /><form className="context-create" onSubmit={(event) => { event.preventDefault(); const input = event.currentTarget.elements.namedItem("capture"); onAddInboxItem(input.value); input.value = ""; }}><label htmlFor="system-capture">Cattura senza chiarire ora</label><div><input id="system-capture" name="capture" placeholder="Nuovo elemento Inbox" /><button className="submit-button" type="submit">Aggiungi</button></div></form></section>}

    {section === "projects" && <section className="panel system-surface"><div className="section-heading"><div><p className="eyebrow">Progetti</p><h2>Risultati che richiedono più azioni</h2></div>{data.projects.length > 0 && <button className="submit-button compact-button" onClick={() => setEditingProject(null)} type="button">Crea progetto</button>}</div>{data.projects.length ? <ul className="project-inventory">{data.projects.map((project) => { const projectActions = data.projectActions.filter((action) => action.projectId === project.id && !action.completed); const noAction = !projectsWithOpenActions.has(project.id); const stale = !project.lastReviewedAt || new Date(project.lastReviewedAt).getTime() < staleThreshold; return <li className="project-inventory-card" key={project.id}><button className="project-inventory-main" onClick={() => setEditingProject(project)} type="button"><div><strong>{project.title}</strong><span>{project.desiredOutcome || "Risultato desiderato da definire"}</span></div><div className="project-flags">{noAction && <span className="warning-flag">Senza prossima azione</span>}{project.status === "blocked" && <span className="warning-flag">Bloccato</span>}{stale && <span>Da revisionare</span>}</div><small>{projectActions.length} azioni aperte · {project.dueDate ? `scadenza ${project.dueDate}` : "nessuna scadenza"}</small></button><button className="delete-button labeled-delete" onClick={() => onDeleteProject(project.id)} type="button">Elimina</button></li>; })}</ul> : <EmptyState action="Crea progetto" onAction={() => setEditingProject(null)}>Nessun progetto attivo.</EmptyState>}</section>}

    {section === "actions" && <UnifiedActions actions={actions} onDelete={onActionDelete} onMoveOrder={onActionOrder} onSave={onActionSave} onToggle={onToggleAction} projects={data.projects} />}
    {section === "calendar" && <CalendarPanel items={data.calendarItems} onDeleteItem={onDeleteCalendarItem} onSaveItem={onSaveCalendarItem} today={date} />}
    {section === "review" && <WeeklyReview agentSlot={<AgentAssist data={data} date={date} mode="weekly-review" onSaveInsight={onSaveAgentInsight} title="Prepara la revisione" />} data={data} date={date} onNavigate={onNavigate} onSave={onSaveWeeklyReview} />}

    {["waiting", "someday", "archive"].includes(section) && (() => { const config = section === "waiting" ? { title: "In attesa", items: data.waitingFor, save: onSaveWaitingFor, remove: onDeleteWaitingFor, fields: [{ key: "person", label: "Persona o soggetto" }, { key: "followUpDate", label: "Data follow-up", type: "date" }, { key: "description", label: "Nota", type: "textarea" }] } : section === "someday" ? { title: "Prima o poi / Forse", items: data.somedayMaybe, save: onSaveSomedayMaybe, remove: onDeleteSomedayMaybe, fields: [{ key: "description", label: "Nota", type: "textarea" }] } : { title: "Archivio", items: data.archiveItems, save: onSaveArchiveItem, remove: onDeleteArchiveItem, fields: [{ key: "content", label: "Contenuto", type: "textarea" }] }; return <section className="panel system-surface"><div className="section-heading"><div><p className="eyebrow">Sistema</p><h2>{config.title}</h2></div>{config.items.length > 0 && <button className="submit-button compact-button" onClick={() => setEditor({ config, item: null })} type="button">Aggiungi elemento</button>}</div>{config.items.length ? <ul className="reference-list">{config.items.map((item) => <li key={item.id}><button onClick={() => setEditor({ config, item })} type="button"><strong>{item.title}</strong><span>{item.description || item.content || "Nessuna nota"}</span></button><button className="delete-button labeled-delete" onClick={() => config.remove(item.id)} type="button">Elimina</button></li>)}</ul> : <EmptyState action="Aggiungi elemento" onAction={() => setEditor({ config, item: null })}>Nessun elemento in {config.title.toLowerCase()}.</EmptyState>}</section>; })()}
  </main><BottomNav activeSection={activeSection} onNavigate={onNavigate} />
  {clarifying && <ClarifyInboxModal item={clarifying} onClose={() => setClarifying(null)} onSubmit={async (result) => { await onClarifyInboxItem(clarifying.id, result); setClarifying(null); }} projects={data.projects} today={date} />}
  {editingProject !== undefined && <ProjectModal onClose={() => setEditingProject(undefined)} onSave={(project) => { onSaveProject(project); setEditingProject(undefined); }} project={editingProject} />}
  {editor && <BasicModal fields={editor.config.fields} item={editor.item} mode={editor.item ? `Modifica ${editor.config.title}` : `Nuovo elemento · ${editor.config.title}`} onClose={() => setEditor(null)} onDownloadAttachment={editor.config.title === "Archivio" ? onDownloadArchiveAttachment : undefined} onSave={(item) => { editor.config.save(item); setEditor(null); }} />}
  </div>;
}
